### ISSUE TITLE
Improve current Python code

### ISSUE THREAD

**Issue by serhii73** [place2live/place2live#129]
If you see what can improve in this project please create an issue or send me the PR.
Happy Hacktoberfest!
![Screenshot from 2019-10-08 21-51-56](https://user-images.githubusercontent.com/24910277/66424196-db8a5680-ea15-11e9-8a5b-23b5d6ca89e5.png)

**Comment by elissavetv** [comment]
Hello! I would like to help. Are there any specific issues you need help with?

**Comment by serhii73** [comment]
> Hello! I would like to help. Are there any specific issues you need help with?

https://github.com/serhii73/place2live/issues/131 - What do you think?
Can you take it?
