### ISSUE TITLE
Add years of life from https://population.io to where.py

### ISSUE THREAD

**Issue by serhii73** [place2live/place2live#138]
http://54.72.28.201/1.0/life-expectancy/total/male/Germany/1998-01-12/?format=json
You can use this API. We see the list of countries:
![Screenshot from 2019-10-10 08-49-49](https://user-images.githubusercontent.com/24910277/66560062-47c4a180-eb5f-11e9-964d-71617cca9ed8.png)
It will be great if you add one column where will be information about how much will live a human in each country.

**Comment by tandelDipak** [comment]
Hi 
I would like to work on this but the above URL is not working from my system. Can you please help.

**Comment by serhii73** [comment]
```
In [2]: import requests                                                                                                                                         

In [3]: url = "https://d6wn6bmjj722w.cloudfront.net/1.0/life-expectancy/remaining/male/Ukraine/2019-10-10/28y2m2d/?format=json"                                 

In [4]: r = requests.get(url)                                                                                                                                   

In [5]: r.json()                                                                                                                                                
Out[5]: 
{'date': '2019-10-10',
 'country': 'Ukraine',
 'age': '28y2m2d',
 'remaining_life_expectancy': 41.78521118490228,
 'sex': 'male'}
```
You can use this URL.

**Comment by serhii73** [comment]
Does that make sense? @tandelDipak

**Comment by tandelDipak** [comment]
Yes, thanks @serhii73. I will work on it and update you.

**Comment by tandelDipak** [comment]
Instead of asking gender what if we query API for both the gender and display it to the user.

**Comment by serhii73** [comment]
Yes. Or you can ask only: "How old are you?"

**Comment by serhii73** [comment]
Do you want to show the data for men and women?
I think output information must not contain neseccery information.
Only important information. 
And I think need to ask, male or female.

**Comment by tandelDipak** [comment]
Ohk, I will modify based on your opinion.

**Comment by naymanuk** [comment]
@serhii73 can you please help me understand how you were able to find the change in URL for population io api - https://d6wn6bmjj722w.cloudfront.net ? They seem to be changing it very frequently so I am thinking I should change the data source for one of my projects.
