### ISSUE TITLE
Add tooltip

### ISSUE THREAD

**Issue by serhii73** [place2live/place2live#142]
yes , we can add new column, additionally we can add feature in case country name entered wrong by user then show with the message the closest country name by match alphabets , ex : user entered Autalia, then message comes: did u mean Australia or Austria

_Originally posted by @roprashar in https://github.com/serhii73/place2live/issues/140#issuecomment-541017103_

**Comment by gillianomenezes** [comment]
Can I do it?

**Comment by serhii73** [comment]
> Can I do it?

Thank you very much for your interest.
Sorry, @roprashar working on this task.
Maybe you can add https://github.com/place2live/place2live/blob/master/english_speaking_population/EnglishSpeakingPopulation.csv this data to where.py output?
![Screenshot from 2019-10-10 08-49-49](https://user-images.githubusercontent.com/24910277/66677790-19d08180-ec73-11e9-81c2-ac9be0ac0674.png)
You can add a new column and add this information, is it ok?
Thank you very much!
