### ISSUE TITLE
Scrape freedomhouse report

### ISSUE THREAD

**Issue by serhii73** [place2live/place2live#150]
https://github.com/place2live/place2live/blob/master/city/city/spiders/lists_of_cities.py#L88-L98 - I want to get CSV with 2 headers, name of country and country's score.
![Screenshot from 2019-10-22 11-49-39](https://user-images.githubusercontent.com/24910277/67270810-0b2f6900-f4c2-11e9-9600-5f259fd9d0a0.png)
You need to extract all countries from here and then gea all scores for the 2018 year.

**Comment by barhenkro** [comment]
Hi, I would like to help with this one

**Comment by barhenkro** [comment]
where would you like the code to be at?
