### ISSUE TITLE
Add the world's most neglected displacement crises to where.py

### ISSUE THREAD

**Issue by serhii73** [place2live/place2live#6]
![62053041_2879800028912029_7087614087659520000_n](https://user-images.githubusercontent.com/24910277/59128258-37fb3d80-8972-11e9-9a17-62451a7aca64.jpg)

**Comment by lexiewh** [comment]
Hi, I can work on this if you would like.

**Comment by serhii73** [comment]
If ready data frame from where.py wants to show these countries, please add a new column(`note`, `remark` or etc) and write there about neglected displacement crises.
Thank you very much!

**Comment by lexiewh** [comment]
Ok, this is my understanding:

If the country is included in the image above (for the neglected displacement crises) then add a note in the new note column of the data frame about the neglected displacement crises.

**Comment by serhii73** [comment]
Exactly.
Thank you very much @lexiewh !

**Comment by serhii73** [comment]
Thank you very much!
